# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - release
  - 0.6.2
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("LorentzVectors",coverage=true)'
